### ISSUE TITLE
awx: Unable to reach built in postgres

### ISSUE THREAD

**Issue by onedr0p** [novumrgi/helm#5]
My deployment:

https://github.com/onedr0p/k3s-gitops/blob/master/deployments/default/awx/awx.yaml
https://github.com/onedr0p/k3s-gitops/blob/master/deployments/default/awx/awx.txt

awx is stuck in the init phase:

```
awx-64b846cbf4-ght2z                              0/3     Init:0/1    1          3m35s
```

logs show:

```
kubetail awx

[awx-64b846cbf4-ght2z init] The above exception was the direct cause of the following exception:
[awx-64b846cbf4-ght2z init]
[awx-64b846cbf4-ght2z init] Traceback (most recent call last):
[awx-64b846cbf4-ght2z init]   File "/usr/bin/awx-manage", line 8, in <module>
[awx-64b846cbf4-ght2z init]     sys.exit(manage())
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
[awx-64b846cbf4-ght2z init]     execute_from_command_line(sys.argv)
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
[awx-64b846cbf4-ght2z init]     utility.execute()
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
[awx-64b846cbf4-ght2z init]     self.fetch_command(subcommand).run_from_argv(self.argv)
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
[awx-64b846cbf4-ght2z init]     self.execute(*args, **cmd_options)
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
[awx-64b846cbf4-ght2z init]     output = self.handle(*args, **options)
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/commands/shell.py", line 92, in handle
[awx-64b846cbf4-ght2z init]     exec(sys.stdin.read())
[awx-64b846cbf4-ght2z init]   File "<string>", line 1, in <module>
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/contrib/auth/models.py", line 162, in create_superuser
[awx-64b846cbf4-ght2z init]     return self._create_user(username, email, password, **extra_fields)
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/contrib/auth/models.py", line 145, in _create_user
[awx-64b846cbf4-ght2z init]     user.save(using=self._db)
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 66, in save
[awx-64b846cbf4-ght2z init]     super().save(*args, **kwargs)
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
[awx-64b846cbf4-ght2z init]     force_update=force_update, update_fields=update_fields)
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
[awx-64b846cbf4-ght2z init]     force_update, using, update_fields,
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table
[awx-64b846cbf4-ght2z init]     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert
[awx-64b846cbf4-ght2z init]     using=using, raw=raw)
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
[awx-64b846cbf4-ght2z init]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
[awx-64b846cbf4-ght2z init]     return query.get_compiler(using=using).execute_sql(return_id)
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1373, in execute_sql
[awx-64b846cbf4-ght2z init]     with self.connection.cursor() as cursor:
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
[awx-64b846cbf4-ght2z init]     return self._cursor()
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
[awx-64b846cbf4-ght2z init]     self.ensure_connection()
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
[awx-64b846cbf4-ght2z init]     self.connect()
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
[awx-64b846cbf4-ght2z init]     raise dj_exc_value.with_traceback(traceback) from exc_value
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
[awx-64b846cbf4-ght2z init]     self.connect()
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
[awx-64b846cbf4-ght2z init]     self.connection = self.get_new_connection(conn_params)
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
[awx-64b846cbf4-ght2z init]     connection = Database.connect(**conn_params)
[awx-64b846cbf4-ght2z init]   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
[awx-64b846cbf4-ght2z init]     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[awx-64b846cbf4-ght2z init] django.db.utils.OperationalError: could not connect to server: Connection refused
[awx-64b846cbf4-ght2z init] 	Is the server running on host "awx-postgresql" (10.43.20.155) and accepting
[awx-64b846cbf4-ght2z init] 	TCP/IP connections on port 5432?
[awx-64b846cbf4-ght2z init]
```

Service is there:

```
awx-postgresql                   ClusterIP      10.43.20.155    <none>           5432/TCP                                                                         5m55s
awx                              ClusterIP      10.43.120.91    <none>           8052/TCP                                                                         5m55s
awx-postgresql-headless          ClusterIP      None            <none>           5432/TCP                                                                         5m55s
```

I do not see any PVC being created, might be the issue..

**Comment by onedr0p** [comment]
n/m named postgresql wrong in the chart, gitea has different naming :P
